frontend-url: http://localhost:3000

server:
  port: 80

# Database Configuartion
spring:
  datasource:
    url: jdbc:mysql://db-ecom.ch28ga62if9j.us-east-1.rds.amazonaws.com:3306/db-ecom
    username: admin
    password: "bpLolOwHf2A9MSpkL2td"
    driver-class-name: com.mysql.cj.jdbc.Driver

# JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

#File upload config
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB

#Role Id
role.admin.id: "200"
role.normal.id: "300"

# Google Login
googleClientId: "google-client-id"
googleSecret: "google-secret"

# JWT Secret Key
application:
  security:
    jwt:
     secret-key: "Z1s8Ck#eF@q5D2$gH7"
     expiration: "3600"
     refresh-token:
      expiration: "604800"

#AWS S3
aws:
  s3:
    accessKey: "AKIA4MTWHBGMS5SJU7PG" 
    secretKey: "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"
    bucketName: "podecombucket"
    region: "us-east-1"
    user-image-path: "user-images/"
    products-image-path: "product-images/"
    categories-image-path: "category-images/"

newPassword: "0000"
