name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Build the backend (Spring Boot)
    - name: Build backend
      run: |
        ./mvnw clean package -DskipTests

    - name: Deploy Backend to EC2
      run: |
        scp -o StrictHostKeyChecking=no -i ${{ secrets.EC2_KEY }} target/QuickPik.jar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/ecom-backend/

        ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_KEY }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/ecom-backend
          pm2 stop ecom-backend || true
          pm2 delete ecom-backend || true
          pm2 start "java -jar /home/ubuntu/ecom-backend/QuickPik.jar" --name ecom-backend
          pm2 save
        EOF
