name: Deploy Backend to EC2

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # Checkout the code

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven  # Enable Maven caching

      - name: Build with Maven
        run: mvn -B package --file pom.xml  # Build the Spring Boot application

      - name: Copy JAR file to EC2
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}  # Your EC2 SSH key
          EC2_USER: ${{ secrets.EC2_USER }}        # Your EC2 user (e.g., ubuntu)
          EC2_HOST: ${{ secrets.EC2_HOST }}        # Your EC2 host (IP or DNS)
        run: |
          scp -i $EC2_SSH_KEY -o StrictHostKeyChecking=no target/QuickPik.jar $EC2_USER@$EC2_HOST:/home/ubuntu/deployment/backend/

      - name: Setup EC2 Instance
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          ssh -i $EC2_SSH_KEY -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            # Update packages
            sudo apt update -y
            
            # Install Java if not already installed
            sudo apt install -y openjdk-17-jdk
            
            # Install Node.js and PM2 if not already installed
            sudo npm install -g pm2
            
            # Create deployment directories if they don't exist
            mkdir -p /home/ubuntu/deployment/backend/
          EOF

      - name: Start Backend with PM2
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          ssh -i $EC2_SSH_KEY -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            # Start the Spring Boot application with PM2
            pm2 start java --name backend -- /home/ubuntu/deployment/backend/QuickPik.jar
            pm2 save
          EOF
